configMapGenerator:
- files:
  - application.yml
  name: 82022874-configmap
resources:
- pvc.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
images:
- name: cepgbaseacr.azurecr.io/troubleshooting:latest
  newTag: "202411050132"
